fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [file, python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ""
    hooks:
      - id: mypy
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args: [--all]
